// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv6q_rvIYxtDIdc99CPwdAWJxoMmFLQoI',
    appId: '1:692926630789:web:43db5c2a705247cba212ec',
    messagingSenderId: '692926630789',
    projectId: 'tripminder-75d7b',
    authDomain: 'tripminder-75d7b.firebaseapp.com',
    storageBucket: 'tripminder-75d7b.firebasestorage.app',
    measurementId: 'G-L1H6TE7ZTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTpnbx2KbQCUszk5ucrHQcgg2L8YPWBS0',
    appId: '1:692926630789:android:3d66939a4c52c236a212ec',
    messagingSenderId: '692926630789',
    projectId: 'tripminder-75d7b',
    storageBucket: 'tripminder-75d7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANPJ3FouZtqJF25iotBA9KcuagqYXjZnw',
    appId: '1:692926630789:ios:2bc97cdfd1fa8b2ba212ec',
    messagingSenderId: '692926630789',
    projectId: 'tripminder-75d7b',
    storageBucket: 'tripminder-75d7b.firebasestorage.app',
    iosBundleId: 'com.example.graduation',
  );
}
